#!/usr/bin/python

import pdb
import argparse
#import rpmpkgclass
from packageclasses.rpm import RpmPackage 

parser = argparse.ArgumentParser(description='cook a recipe')
parser.add_argument('filename')
parser.add_argument("--verbose", help="verbose output", action="store_true")
parser.add_argument("--speconly", help="only create a spec file", action="store_true")
args = parser.parse_args()


#pdb.set_trace()
'''
if args.idebug:
    print "debug on"
else:
    print "debug off"
'''
if args.verbose:
    print "verbose output on"

print "COOKING ..."
print args.filename

execfile(args.filename)
#pdb.set_trace()
p = TestPackage()
#p.setup(args)
p.build(args)
#pdb.set_trace()

