#!/usr/bin/python

import pdb
import argparse
from packageclasses.rpm import RpmPackage 

parser = argparse.ArgumentParser(description='cook a recipe')
parser.add_argument('filename')
parser.add_argument("--verbose", help="verbose output", action="store_true")
parser.add_argument("--speconly", help="only create a spec file", action="store_true")
args = parser.parse_args()


if args.verbose:
    print "verbose output on"

print "COOKING ..."
print args.filename

execfile(args.filename)
#import epdb; epdb.st()
p = TestPackage()
p.build(args)
